# Auto-generated by Firmgen — DO NOT EDIT.
# Explicit list of firmware sources + include dirs, refreshed before every
# build. Replaces the old file(GLOB ...) (which cached stale results and could
# escape the project). FW_ROOT is set by the including main/CMakeLists.txt.

set(APP_SOURCES
    "${FW_ROOT}/app/app.c"
    "${FW_ROOT}/platforms/esp32/led_platform.c"
    "${FW_ROOT}/platforms/esp32/sensor_platform.c"
    "${FW_ROOT}/services/anomaly_detector.c"
    "${FW_ROOT}/services/baseline_learner.c"
    "${FW_ROOT}/services/commissioning.c"
    "${FW_ROOT}/services/dashboard.c"
    "${FW_ROOT}/services/operating_state.c"
    "${FW_ROOT}/services/telemetry.c"
    "${FW_ROOT}/utils/helpers/helpers.c"
    "${FW_ROOT}/utils/logger/logger.c"
)

set(FW_INCLUDE_DIRS
    "${FW_ROOT}"
    "${FW_ROOT}/app"
    "${FW_ROOT}/configs"
    "${FW_ROOT}/interfaces"
    "${FW_ROOT}/platforms/esp32"
    "${FW_ROOT}/services"
    "${FW_ROOT}/utils/helpers"
    "${FW_ROOT}/utils/logger"
)
